### ISSUE TITLE
Изначальное состояние лейаута сломано

### ISSUE THREAD

**Issue by irbisadm** [funrozen/angular_videoconf-#2]
![image](https://user-images.githubusercontent.com/575439/102914768-d89c4a00-4491-11eb-9d43-d9c9200a4ae1.png)

**Comment by funrozen** [comment]
it is pretty tricky to repeat original behavior so I just added a curtain
![Снимок экрана 2020-12-25 в 00 41 04](https://user-images.githubusercontent.com/75640574/103106885-4e4b1600-464a-11eb-957b-e6ef278f0895.png)
